### ISSUE TITLE
Issue on Compilation

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [mageprince/magento2-extrafee#1]
**Steps to reproduce**

    Fresh install of 2.1.6 on PHP 7.0.15
    Complete install process via web browser
    Install extension

    run command 
         cd <Magento install directory>
         php bin/magento setup:upgrade
         php bin/magento setup:di:compile

**Expected result**

    It to run without issue

**Actual result**

Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 42.0 MiProxies code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiRepositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiBPHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting ')' in /var/www/html/magento-2/app/code/Prince/Extrafee/Block/Sales/Order/Fee.php on line 44

**Comment by mageprince** [comment]
Hi dodiya-divyarajsinh,
Thank you for posting issue. Issue has been solved. Please check again with compilation.
