### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by Fgruntjes** [mageprince/magento2-extrafee#10]
Hello,

Would you consider start tagging the module to use something like semantic versioning? This would make it allot easier to depend on the module and follow bugfixes, features and breaking changes.

Thnx!

**Comment by mageprince** [comment]
HI @Fgruntjes Thanks for the suggestion and recent improvements for this module. I added releases with description.
https://github.com/mageprince/magento2-extrafee/releases
