### ISSUE TITLE
Enhancement: Multiple extra fee lines?

### ISSUE THREAD

**Issue by firehorsecreative** [mageprince/magento2-extrafee#14]
I have a customer that needs to be able to add multiple extra fee lines instead of totaling the extra fees into one line. For example, if the customer adds 3 products into their cart, there should be 3 extra fee lines added. Is it possible for you to add this functionality? We would be willing to pay for your time.

**Comment by mageprince** [comment]
@firehorsecreative Thank you for posting issue.
This module does not provide this functionality. We will add this functionality in next version of this module.

**Comment by mageprince** [comment]
Hi @firehorsecreative New module now live on the Magento Marketplace which support multiple extra fee with lots of new features. You can download it from here: [Magento 2 Extra Fee Pro](https://marketplace.magento.com/prince-magento2-extrafeepro.html)

**Comment by kanhaiya-farzi** [comment]
Hi Prince,

Can you please let me know how to implement checkbox before extra fee label so that it can be available for user chice that he want to pay this amount or not. By clicking on the checkbox, amount should be calculated on subtotal.

Let me know so that I can implement this feature.
