### ISSUE TITLE
Extra fee is not present in Email templates

### ISSUE THREAD

**Issue by emq-vedant** [mageprince/magento2-extrafee#16]
Everything works fine except the extra fee is not displaying in email templates.

The extra fee [ Delivery Charges ] is displaying in adminarea orders total:
![admin_order_totals](https://user-images.githubusercontent.com/38646517/39112630-b26c771a-46f6-11e8-9656-81d3472fa13d.png)

<br>

But extra fee [ Delivery Charges ] is not displaying in order emals:
![email_template](https://user-images.githubusercontent.com/38646517/39112663-ca946a14-46f6-11e8-8b64-faa8dfc21741.png)

**Comment by mageprince** [comment]
Hi @emq-vedant, Thank you for your report. Let me check and update on this issue.

**Comment by emq-vedant** [comment]
Yes @mageprince , for your information I am using Magento version 2.2.2

**Comment by mageprince** [comment]
@emq-vedant I checked this issue with default Magento 2.2.2 and it's working fine. Check below screenshot. Please download the latest code from GitHub and check.
![invoice for your main website store order mail mageprince gmail com gmail](https://user-images.githubusercontent.com/24751863/39260582-92cfdf72-48d7-11e8-9e50-8856e3b1713f.png)

**Comment by emq-vedant** [comment]
Yes @mageprince , you are right. With the default blank theme and latest extension code, the extra fee is displaying in email templates.

I noticed following two things:

1) When I check the admin area, inside Invoice > Print, the extra fee is not displaying in PDF.

2) If I override those email layouts in my child theme then the extra fee is not displaying in email templates.
