### ISSUE TITLE
Always 0.00 Fess apply 

### ISSUE THREAD

**Issue by ghost** [mageprince/magento2-extrafee#17]
I have set Extra fees in configuration, but same fees do not apply at While placing an order. Even no any extra fees display in total section. 0.00 Fees display in order view.

**Comment by mageprince** [comment]
@navinbhudiya thank you for your report. Let me check and update same.

**Comment by mageprince** [comment]
@navinbhudiya It's working fine.
Please check that if any third party module conflicts. Use latest repository code and check with default Magento setup.

Check the screenshot for configuration settings

![configuration settings stores magento admin](https://user-images.githubusercontent.com/24751863/42234357-ebbd1814-7f11-11e8-937a-2a3fa3c122c0.png)
