### ISSUE TITLE
Extra feed not included in Orderdata when using API?

### ISSUE THREAD

**Issue by niekv** [mageprince/magento2-extrafee#18]
Hi,

It seems that the calculated Extra fee is not accessible when using a GET for the order, for example:

`/rest/V1/orders/{order_id}`

Is this correct? If so, could you add this in a future release?  

Thanks

**Comment by mageprince** [comment]
Hi, @niekv Thanks for your suggestion. I will add this in a future version of this module.

**Comment by mageprince** [comment]
Hi, @niekv I have just add extrafee attribute in `/rest/V1/orders/{order_id}` 
 Please download latest repository or check commit: [1a60694](https://github.com/mageprince/magento2-extrafee/commit/1a606945c6a60dfe7500d603ffc3d9e6c8eb8c18)

**Comment by niekv** [comment]
@mageprince Great! Thanks for the update.
