### ISSUE TITLE
Percentage instead of Fixed Price

### ISSUE THREAD

**Issue by murtazakarimi** [mageprince/magento2-extrafee#2]
Hey Prince,

Great job with this module. However is it possible to change the fixed price to percentage? I mean instead of $10 use 10% of cart total?

Let me know.

Thanks,

**Comment by mageprince** [comment]
Hi @murtazakarimi ,
Thanks for the suggestion. I will add this functionality in next version of the module. You can add your logic in `app/code/Prince/Extrafee/Model/Total/Fee.php`

**Comment by vijay9839** [comment]
Hi Prince ,


I downloaded zip file and did not find repo folder . can u explain how to install. I have to much error to installing it.

**Comment by mageprince** [comment]
@murtazakarimi 
I added percentage price functionality to this module. Please download the latest module or install module via composer.
