### ISSUE TITLE
Not Working in Magento 2.2.5

### ISSUE THREAD

**Issue by Payless** [mageprince/magento2-extrafee#21]
I installed the module in magento 2.2.5 but it's not working, i flush the cache, run di:compile and also deployed the content, i have also checked the file permission.
It's only showing configuration in admin but not working in frontend.

**Comment by mageprince** [comment]
Hi, @Payless Thanks for your report. This module is tested with default Magento 2.1.x to 2.2.2. I will test it later versions of Magento and let you know if found any issue.

**Comment by Payless** [comment]
Hi,

I'm away on a team development afternoon and then off for the weekend. If its Urgent please call 1300 658 610 until 5.30pm AEST Friday and speak to one of our team members.

Look forward to working with you on my return Monday Morning.

Have a great weekend!
.

Guy Dawson |

Payless Promotions

P: 1300 658 610

E: guy@paylesspromotions.com.au

Website<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.paylesspromotions.com.au%2F&e=c06c7bd6&h=585d9e53&f=y&p=y> | Facebook<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.facebook.com%2FPaylessPromotions&e=c06c7bd6&h=71a569aa&f=y&p=y>

**Comment by mageprince** [comment]
Hi @Payless, Recently I tested this module in Magento 2.2.3, 2.2.4 and 2.2.5 and it's working without any issue. Please check it with default Magento installation.

**Comment by Payless** [comment]
Thanks for your email,

Our office is currently not open until 8.30am in the morning. We appreciate your email and will get back to you ASAP.

Guy Dawson |

Payless Promotions

P: 1300 658 610

E: guy@paylesspromotions.com.au

Website<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.paylesspromotions.com.au%2F&e=c06c7bd6&h=585d9e53&f=y&p=y> | Facebook<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.facebook.com%2FPaylessPromotions&e=c06c7bd6&h=71a569aa&f=y&p=y>

**Comment by Payless** [comment]
It's not showing the extra price in shopping cart page but, please refer the attached screenshots.
![configuration settings stores magento admin](https://user-images.githubusercontent.com/8840041/43695635-6eb40944-9957-11e8-9642-7413544c57a8.png)
![shopping cart 1](https://user-images.githubusercontent.com/8840041/43695639-72c5d882-9957-11e8-8859-5cd189a661d2.png)
![checkout](https://user-images.githubusercontent.com/8840041/43695644-754f33a0-9957-11e8-8640-2418c5cdef64.png)
