### ISSUE TITLE
Does not work with Paypal

### ISSUE THREAD

**Issue by arundharani1686** [mageprince/magento2-extrafee#22]
When extra fee is added we cannot complete the payment with Paypal. It throws the error as shown below

PayPal gateway has rejected request. The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details).

**Comment by mageprince** [comment]
@arundharani1686, Thank you for your report. I will solve this issue in the next version of this module.

**Comment by minhducnho** [comment]
hi @mageprince are you solve this issue?

**Comment by mageprince** [comment]
@arundharani1686 @minhducnho This issue has been solved. Please check commit: https://github.com/mageprince/magento2-extrafee/pull/29/commits/d6863800cd25ddc468e37f7345d3ec6bd51721a7
