### ISSUE TITLE
Extra Fee by Allowed Countries

### ISSUE THREAD

**Issue by webusat** [mageprince/magento2-extrafee#24]
Hi,

I tried to get this module to work only for specified countries by adding it to system.xml but so far we haven't been able to do so.  Can you help?

Stan

**Comment by webusat** [comment]
Hi!

Any chance on getting this added?

Thanks,
Stan

**Comment by mohamedhk2** [comment]
+1

**Comment by mageprince** [comment]
Hi @webusat @mohamedhk2 We have added multicurrency supports in latest version 2.3.1. You can download from Magento Marketplace: https://marketplace.magento.com/prince-magento2-extrafee.html
