### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by joshuahaber** [mageprince/magento2-extrafee#25]
Is there a way you know of to hide the shipping fee in the order summary if the shipping is set to 0 or free?  I don't mind donating if you can help!

**Comment by makproductions** [comment]
You could either hide it using javascript (not the best option), or modify the module. Before it adds the additional fee you could check the shipping total and prevent the fee from being added.

**Comment by joshuahaber** [comment]
Could you give me an example of how that could be done?  What file and what I would need to do?



[http://www.newrockit.com/wp-content/uploads/2016/10/ICON.png]
Josh Haber
m:      318.348.0448<tel:318.348.0448>
w:      www.newrockit.com<http://www.newrockit.com/>  e: josh@newrockit.com<mailto:josh@newrockit.com>



On Oct 24, 2018, at 12:35 AM, makproductions <notifications@github.com<mailto:notifications@github.com>> wrote:


You could either hide it using javascript (not the best option), or modify the module. Before it adds the additional fee you could check the shipping total and prevent the fee from being added.

**Comment by webusat** [comment]
@joshuahaber So are you saying to don't want to charge the extra fee if the shipping is $0 or free?

**Comment by joshuahaber** [comment]
So here’s the gist of what I’m trying to do.

After an order hits $107 I want your plugin to charge 7% of the order as “shipping”.

I’ve got free shipping working after $107 but I want that to be hidden in the right column and if possible under the shipping methods.



[image1.jpeg]


[image2.jpeg]


[http://www.newrockit.com/wp-content/uploads/2016/10/ICON.png]
Josh Haber
m:      318.348.0448<tel:318.348.0448>
w:      www.newrockit.com<http://www.newrockit.com/>  e: josh@newrockit.com<mailto:josh@newrockit.com>



On Oct 24, 2018, at 10:31 AM, Matt6 Studios, LLC <notifications@github.com<mailto:notifications@github.com>> wrote:


@joshuahaber<https://github.com/joshuahaber> So are you saying to don't want to charge the extra fee if the shipping is $0 or free?

**Comment by webusat** [comment]
@joshuahaber Hey Josh, I am not the developer.  I was just was trying to help.

Next, the plugin charges a flat fee, not a percentage.  So the Model would have to change.

After that, when you say hidden, do you also not what it to add to the total or just not bee seen?

**Comment by joshuahaber** [comment]
It does both


switch ($this->helper->getPriceType()) {
        case PriceType::TYPE_FIXED:
        return $this->objectManager->get(Calculator\FixedCalculator::class);
        case PriceType::TYPE_PERCENTAGE:
        return $this->objectManager->get(Calculator\PercentageCalculator::class);
        case PriceType::TYPE_PER_ROW:
        return $this->objectManager->get(Calculator\PerRowCalculator::class);
        case PriceType::TYPE_PER_ITEM:
        return $this->objectManager->get(Calculator\PerItemCalculator::class);
        default:
        throw new ConfigurationMismatchException(__('Could not find price calculator for type %1', $this->helper->getPriceType()));
        }




What I'm trying to do is hide the "default" shipping (which is 0 based on the shipping rules I created).



[http://www.newrockit.com/wp-content/uploads/2016/10/ICON.png]
Josh Haber
m:      318.348.0448
w:      www.newrockit.com<http://www.newrockit.com/>  e: josh@newrockit.com<mailto:josh@newrockit.com>


________________________________
