### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by Tjitse-E** [mageprince/magento2-extrafee#27]
Hi,

Thanks for your efforts on this module!

Can you create a new release on Github so we can use composer correctly? The last release is 2.1.1, but after that there were commits made to the master branch.

**Comment by mageprince** [comment]
Hi @Tjitse-E I have created release with tag 2.1.2 : 
https://github.com/mageprince/magento2-extrafee/releases/tag/2.1.2

**Comment by Tjitse-E** [comment]
@mageprince don't forget to change the version in composer.json: https://github.com/mageprince/magento2-extrafee/blob/master/composer.json#L10
