### ISSUE TITLE
For Making this extension as Custom Discount

### ISSUE THREAD

**Issue by niravamodi** [mageprince/magento2-extrafee#3]
Hi Prince,
Grate extension, Thanks for your contribution, but I want to make this extension as "Custom Discount" extension instead of Fee. So can you please let me know what are the changes I will need to do for that?

**Comment by mageprince** [comment]
HI @niravamodi ,
You need to change namespace to `Prince\CustomDiscount` from every file of this extension.

**Comment by niravamodi** [comment]
Hi Prince,
Thanks for Quick reply, I know I will need to change namespace, but for now I just want to know what change I will need to do in model file (Prince/Extrafee/Model/Total/Fee.php). Like for example, I will need to change $balance = $fee - $exist_amount; line to $balance = **-** $fee - $exist_amount;. So I did this change in this extension but in Grand Total it is getting deducted twice. So for example my Subtotal is $75 and Discount Amount is $10 then It is showing wrong Grand total Like $55, actually it should be $65. So please let me know which other changes I will need to do?

Also Please give me your email Id or any Messenger ID, so I can directly contact you.

Thanks,
Nirav Modi

**Comment by mageprince** [comment]
Hi @niravamodi ,

Which version of magento do you use?

**Comment by niravamodi** [comment]
Magento ver. 2.1.6

**Comment by niravamodi** [comment]
Enterprise Edition...

**Comment by niravamodi** [comment]
Any Idea @mageprince ?

**Comment by mageprince** [comment]
Comment line number 44 and 50
`$total->setTotalAmount('fee', $balance);`
`$total->setGrandTotal($total->getGrandTotal() + $balance);`
Then try.

**Comment by niravamodi** [comment]
I have commented both the lines, but now it is not deducting any amount. So if the Subtotal is $48 and Discount is $4, then it is showing $48 as Order Total (Grand Total) ...

**Comment by mageprince** [comment]
HI @niravamodi 

I face this issue on Magento 2.2. In Magento 2.2 they change the logic of collectTotals() which makes this issue.
You just need to comment this line: `$total->setTotalAmount('fee', $balance);`
Then delete all products from cart and re-addtocart product to see chnages.

I will update this extension later with compatible with Magento 2.2

Thank You
Prince
