### ISSUE TITLE
Paypal payment option not showing to me

### ISSUE THREAD

**Issue by victorsanva** [mageprince/magento2-extrafee#30]
Hello,

Plugin is working fine to me, but paypal option is not showing me, 

Magneto Version 2.3.4, paypal configuration is with the version incluided in magento, anything strange. 

thank you
![Sin título](https://user-images.githubusercontent.com/60794660/90309686-e4c43980-deea-11ea-9c38-5a09c9c1831d.png)

**Comment by mageprince** [comment]
Hi @victorsanva This is the wrong repository. Please create an issue in https://github.com/mageprince/magento2-paymentfee
