### ISSUE TITLE
Not reflect in order total

### ISSUE THREAD

**Issue by Atranaz** [mageprince/magento2-extrafee#32]
I am using an extra fee for Cash on delivery it showing on the summary but not reflecting in the order total 

When I inspect I found this issue 

**fees-information** - V1/mageprince_extrafeepro/guest-carts/frSH99gjzIj8XbLNQDHsP1991Kz7KASt/fees-information
t**otals-information** - V1/guest-carts/frSH99gjzIj8XbLNQDHsP1991Kz7KASt/totals-information

**fees-information** load before **totals-information** and it cause issue for not reflecting extra fee in order total

I a using Magento 2.3.3

**Comment by mageprince** [comment]
Hi @Atranaz, Thanks for contacting us.
There is no sort-order issue with fee calculation with this module. Here you can check the sort-order of totals: `Mageprince/ExtrafeePro/etc/sales.xml`

Here are some steps to debug your issue:
1. Check third-party modules which override the sales module
2. Check `total_segments` in totals-information for `mageprince_extrafeepro` segment
3. If an extra fee segment not available then there must be an issue with third party customization
4. Disable all third-party extensions or try with fresh Magento isntallation.

**Comment by Atranaz** [comment]
ok, I'll check and update here the result.
