### ISSUE TITLE
Fee only for specific product in cart

### ISSUE THREAD

**Issue by otterbachphilip** [mageprince/magento2-extrafee#33]
Hello!

Is it possible to enable the extra fee only for one product in the cart? 
### **Example:**
In Extrafee Pro i created a condition for Productgroup A. In my Cart i have Productgroup A und Productgroup B. But the fee is applied to the subtotal so the fee is too high. 
I want to apply the extra fee only to Productgroup A and not to the subtotal.

Greetings
Philip

**Comment by mageprince** [comment]
Dear @otterbachphilip, thank you for your report.

Unfortunately, it is not possible to apply an extra fee for a specific product. An extra fee will be applied to the order total.
