### ISSUE TITLE
mini cart not updating on "Add to cart" button

### ISSUE THREAD

**Issue by DeepikaGN31** [mageprince/magento2-extrafee#36]
When clicking on add to cart button even when subtotal is greater then the value set (here 250) minicart still show the extra fee line .

Here is video showing the issue mentioned: 

https://www.awesomescreenshot.com/video/24665025?key=20209b6cd50f505641fa2f9b68254481

Thank you.

**Comment by mageprince** [comment]
Hello @DeepikaGN31, The additional fee line visible on the minicart is a result of custom development implemented for your project. Our extension facilitates the addition of extra fees on both the cart and checkout pages. Kindly reach out to your developer to address this issue.
