### ISSUE TITLE
PriceType does not exist

### ISSUE THREAD

**Issue by justnajm** [mageprince/magento2-extrafee#4]
Kindly look into this issue, unable to run the module properly

1 exception(s):
Exception #0 (ReflectionException): Class Prince\Extrafee\Model\Config\Source\PriceType does not exist

Exception #0 (ReflectionException): Class Prince\Extrafee\Model\Config\Source\PriceType does not exist

**Comment by mageprince** [comment]
@justnajm Thank you for posting issue. But I cannot reproduce this issue in default Magento setup. I recently update this module to support percentage price. Please download and install the latest module in default Magento setup and reopen this issue if you face same error.
