### ISSUE TITLE
Exception on configuration

### ISSUE THREAD

**Issue by alexbogias** [mageprince/magento2-extrafee#5]
Exception #0 (Exception): Notice: Array to string conversion in vendor/magento/framework/Data/Form/Element/AbstractElement.php on line 259
/vendor/magento/framework/Data/Form/Element/AbstractElement.php(259): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '...', 259, Array)

**Comment by mageprince** [comment]
**@alexbogias** thank you for your report.
This issue has been resolved please update magento2-extrafee/etc/adminhtml/system.xml with latest branch code.
