### ISSUE TITLE
Paypal breaks with the module

### ISSUE THREAD

**Issue by himanshug-eh** [mageprince/magento2-extrafee#6]
Hi,

It is good to see the module but it breaks for payment :(

After enabling the module, the paypal does not work (gives error message and does not redirect to paypal) since it is not able to get the cart items.  I have debugged the cart_items and the array is empty with module enabled.   It works after disabling it.

vendor/module-paypal/Model/Api/AbstractApi.php

  ```
  protected function _exportLineItems(array &$request, $i = 0)

        // add cart line items
        $items = $this->_cart->getAllItems();
        file_put_contents("/var/www/html/var/log/paypal-debug.log", print_r($items, true).PHP_EOL, FILE_APPEND);
        if (empty($items) || !$this->getIsLineItemsEnabled()) {
            return;
        }
```
returns the following empty array

Array
(
)

When the module is disabled, the array lists the shopping cart items and paypal works.

**Comment by himanshug-eh** [comment]
Error message by Paypal:

[2018-01-26 14:07:14] main.CRITICAL: Exception message: PayPal gateway has rejected request. The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details).

I have disabled "Transfer Cart Line Items" but still paypal gateway throws the error.

**Comment by mageprince** [comment]
Hi **@himanshu-garg**
Thanks for posting issue. The issue has been solved please download latest repository.
