### ISSUE TITLE
Specific payment method

### ISSUE THREAD

**Issue by msliman** [mageprince/magento2-extrafee#7]
Hi, It is nice work. how can I make fee appear only for specific payment method like cash on delivery ?

**Comment by mageprince** [comment]
@msliman Extrafee extension does not provide this type of functionality. This extension adds extra fee on the total of the order. It's not based on shipping or payment method.

**Comment by mageprince** [comment]
@msliman Please check my new Magento 2 extension: https://marketplace.magento.com/prince-magento2-paymentfee.html This extension adds the extra fee by selecting a specific payment method.
