### ISSUE TITLE
Calculate Tax on Extra Fee

### ISSUE THREAD

**Issue by himanshug-eh** [mageprince/magento2-extrafee#8]
Hi,

It will be good to calculate tax on extra fee too.  Currently, the tax is only calculated on subtotal and shipping.

**Comment by mageprince** [comment]
@himanshu-garg, Thank you for your suggestion. We will add this as configuration settings in next version of this module.

**Comment by niekv** [comment]
@mageprince Any news on this? This addition would be great.

**Comment by Sil-B** [comment]
@mageprince Is TAX working in the paid version? Let me know so i can buy it.

**Comment by mageprince** [comment]
@himanshug-eh @niekv @Sil-B 

This feature now added in the latest version of the Module. You can now enable/disable tax calculation and also select tax class for the extra fee.

Please download the latest version of the module. [Download](https://marketplace.magento.com/prince-magento2-extrafee.html)

**Comment by Sil-B** [comment]
@mageprince thanks!
