### ISSUE TITLE
Use packagist

### ISSUE THREAD

**Issue by Fgruntjes** [mageprince/magento2-extrafee#9]
Hello,

How about putting the module on https://packagist.org/? This would remove the need for the extra repository configuration.

**Comment by Fgruntjes** [comment]
I have added the package now (https://packagist.org/packages/mageprince/magento2-extrafee) but am more than happy to abandon it so you can take ownership and also configure the github hooks for auto update.

Please let me know when and if you are willing to do this.

**Comment by mageprince** [comment]
Hi @Fgruntjes Thank you for your suggestion.
This is a good idea to put a module on  https://packagist.org/ I will add all modules to packagist.
But I face this error on packagist  **The vendor is already taken by someone else** So please remove this module from packagist so I can put all modules to packagist.

**Comment by Fgruntjes** [comment]
Thank you very much, I have deleted the package so you can take ownership.

**Comment by mageprince** [comment]
Hi @Fgruntjes Thank you for your suggestion and support.
I will add this module to https://packagist.org/
